// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmjC297b3oRxT7q2tH6_9dAQAqTk_5urM',
    appId: '1:868646769747:android:b66a0be19b7b18134ae2a6',
    messagingSenderId: '868646769747',
    projectId: 'fir-demo-ea9bb',
    databaseURL: 'https://fir-demo-ea9bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-ea9bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUqyWM0Vywz61o1J5KERvUWcQMQnk0Ah8',
    appId: '1:868646769747:ios:006003494c7a75ca4ae2a6',
    messagingSenderId: '868646769747',
    projectId: 'fir-demo-ea9bb',
    databaseURL: 'https://fir-demo-ea9bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-ea9bb.appspot.com',
    iosClientId: '868646769747-f9m9ljat85rcupq6iauhejcv28tr67ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemoApp',
  );
}
